---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
stringData:
  .dockerconfigjson: >-
    {{ .Values.secretDockerConfigJSON | indent 4}}
type: kubernetes.io/dockerconfigjson
---
kind: Secret
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
stringData:
  spring_datasource_username: {{ .Values.secretBackendPsqlUser }}
  spring_datasource_password: {{ .Values.secretBackendPsqlPassword }}
  spring_data_mongodb_uri: mongodb://{{ .Values.secretBackendMongoUser }}:{{ .Values.secretBackendMongoPassword }}@{{ .Values.secretBackendMongoHost }}:{{ .Values.secretBackendMongoPort }}/{{ .Values.secretBackendMongoDatabase }}?tls=true
  psql_user: {{ .Values.secretBackendPsqlUser }}
  psql_password: {{ .Values.secretBackendPsqlPassword }}
  psql_host: {{ .Values.secretBackendPsqlHost }}
  psql_dbname: {{ .Values.secretBackendPsqlDatabase }}
  psql_port: "{{ .Values.secretBackendPsqlPort }}"
type: Opaque
