stages:
  - module-pipelines

backend:
  stage: module-pipelines
  trigger:
    include:
      - local: "backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

frontend:
  stage: module-pipelines
  trigger:
    include:
      - local: "frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*
