version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: backend
    expose:
      - "8081"
    networks:
      - momo_store
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: frontend
    expose:
      - "80"
    ports:
      - "8081:80"
    networks:
      - momo_store
    restart: unless-stopped

networks:
  momo_store:
    name: momo_store
    driver: bridge