---
kind: Secret
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
stringData:
  spring_datasource_username: $BACKEND_PSQL_USER
  spring_datasource_password: $BACKEND_PSQL_PASSWORD
  spring_data_mongodb_uri: mongodb://$BACKEND_MONGO_USER:$BACKEND_MONGO_PASSWORD@$BACKEND_MONGO_HOST:$BACKEND_MONGO_PORT/$BACKEND_MONGO_DATABASE?tls=true
  psql_user: $BACKEND_PSQL_USER
  psql_password: $BACKEND_PSQL_PASSWORD
  psql_host: $BACKEND_PSQL_HOST
  psql_dbname: $BACKEND_PSQL_DBNAME
  psql_port: "$BACKEND_PSQL_PORT"
type: Opaque
