---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "momo-store-chart.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "momo-store-chart.labels" . | nindent 4 }}
spec:
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "momo-store-chart.name" . }}
  metrics:
    {{- if .Values.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.targetMemoryUtilizationPercentage }}
    {{- end }}
