stages:
  - release
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  

release:
  stage: release
  environment:
    name: staging
    url: https://std-022-44.k8s.praktikum-services.tech
  image: alpine/k8s:1.28.2
  script:
    - helm package helm --destination ./ --app-version $VERSION --version $VERSION
    - curl -v -u $NEXUS_REPO_USER:$NEXUS_REPO_PASS "$NEXUS_REPO_URL/$NEXUS_REPO_HELM_NAME/" --upload-file ./sausage-store-chart-$VERSION.tgz
    - curl -v -u $NEXUS_REPO_USER:$NEXUS_REPO_PASS -X POST "$NEXUS_URL/service/rest/v1/search/assets/download?sort=version&repositoryName=$NEXUS_REPO_HELM_NAME&format=helm"
  when: manual

deploy:
  stage: deploy
  environment:
    name: staging
    url: https://std-022-44.k8s.praktikum-services.tech
  image: alpine/k8s:1.28.2
  before_script:
    - cat helm/values.yaml | envsubst > helm/values.yaml
    - mkdir -p ~/.kube
    - echo "$KUBECONFIGFILE" >> ~/.kube/config    
  script:
    - helm repo add nexus --username "${NEXUS_REPO_USER}" --password "${NEXUS_REPO_PASS}" $NEXUS_REPO_URL/$NEXUS_REPO_HELM_NAME
    - helm repo update
    - helm upgrade --atomic --timeout 15m --version $VERSION --install sausage-store nexus/sausage-store-chart
  after_script:
    - rm -rf ./secret.yaml
    - rm ~/.kube/config
  when: manual

