---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "gitlab.praktikum-services.ru:5050": {
          "auth": "{{ .Values.dockerRegistryAuth }}"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
