version: '3'

services:
  certbot:
    image: certbot/certbot:latest
    env_file: ./.certbot.env
    volumes:
      - letsencrypt:/etc/letsencrypt
      - webroot:/var/www/html
    networks:
      - sausage_store
    entrypoint: /bin/sh -c "chmod +x /home/certbot.sh && /home/certbot.sh"

  blue: &service-backend-definition
    image: gitlab.praktikum-services.ru:5050/std-022-044/sausage-store/sausage-backend:latest
    env_file: ./.backend.env
    environment:
      - VIRTUAL_HOST=backends
    expose:
      - "8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    networks:
      - sausage_store
    restart: unless-stopped

  green: *service-backend-definition

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-022-044/sausage-store/sausage-frontend:latest
    env_file: ./.frontend.env
    environment:
      - DEFAULT_HOST=backends
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt:/etc/letsencrypt:ro
      - webroot:/home/certbot:ro
    networks:
      - sausage_store
    restart: unless-stopped

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-022-044/sausage-store/sausage-backend-report:latest
    container_name: sausage-report
    env_file: ./.report.env
    expose:
      - "8080"
    ports:
      - "8081:8080"
    networks:
      - sausage_store
    restart: unless-stopped

volumes:
  letsencrypt:
  webroot:

networks:
  sausage_store:
    driver: bridge