pipeline {
    agent any // Выбираем Jenkins агента, на котором будет происходить сборка: нам нужен любой

    triggers {
        pollSCM('H/5 * * * *') // Запускать будем автоматически по крону примерно раз в 5 минут
    }

    tools {
        maven 'maven' // Для сборки бэкенда нужен Maven
        jdk 'JDK16' // И Java Developer Kit нужной версии
        nodejs 'node-js-16' // А NodeJS нужен для фронта
    }

    environment {
        TELEGRAM_ACCESS = credentials('d50787e9-c853-4dc2-9d09-d85627d942a8')
    }

    stages {
        stage('Build & Test backend') {
            steps {
                dir("backend") { // Переходим в папку backend
                    sh 'mvn package' // Собираем мавеном бэкенд
                }
            }

            post {
                success {
                    junit 'backend/target/surefire-reports/**/*.xml' // Передадим результаты тестов в Jenkins
                }
            }
        }

        stage('Build frontend') {
            steps {
                dir("frontend") {
                    sh 'npm install' // Для фронта сначала загрузим все сторонние зависимости
                    sh 'npm run build' // Запустим сборку
                }
            }
        }
        
        stage('Save artifacts backend') {
            steps {
                archiveArtifacts(artifacts: 'backend/target/sausage-store-0.0.1-SNAPSHOT.jar')
            }
            post {
                success {
                    sh("curl -X POST -H \'Content-type: application/json\' --data \'{\"chat_id\": \"${TELEGRAM_ACCESS_USR}\", \"text\": \"std-022-044 собрал приложение backend.\" }\' https://api.telegram.org/bot$TELEGRAM_ACCESS_PSW/sendMessage")
                }
            }
        }

        stage('Save artifacts frontend') {
            steps {
                archiveArtifacts(artifacts: 'frontend/dist/frontend/*')
            }
            post {
                success {
                    sh("curl -X POST -H \'Content-type: application/json\' --data \'{\"chat_id\": \"${TELEGRAM_ACCESS_USR}\", \"text\": \"std-022-044 собрал приложение frontend.\" }\' https://api.telegram.org/bot$TELEGRAM_ACCESS_PSW/sendMessage")
                }
            }
        }

    }
}