---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "sausage-store-chart.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "sausage-store-chart.fullname" . }}
  updatePolicy:
    updateMode: "{{ .Values.updateMode }}"
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.containerPolicies | nindent 6 }}
