---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sausage-store-chart.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sausage-store-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.targetPort }}
  selector:
    {{- include "sausage-store-chart.selectorLabels" . | nindent 4 }}